name: 'GitHub Pull Request Labeler'
description: 'Labels PRs based on their size.'

author: 'Ankur Mehta, Chris Carini, and Sulabh Bansal'

branding:
  icon: bell
  color: blue

inputs:
  GITHUB_TOKEN:
    description: 'Default to {{ github.token }}. This is the default GitHub token available to actions and is used to run the action and to post the comments on PRs. The default token permissions (https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) work fine.'
    default: '${{ github.token }}'
    required: false

runs:
  using: 'node16'
  main: '../../dist/labeler/index.js'