name: 'Testing GitHub Pull Request Reminder action'
on:
  schedule:
    - cron: "0 * * * *" # run every hour

  pull_request:

  workflow_dispatch:

jobs:
  test-gh-github-pull-request-reminder-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Data
        shell: bash
        run: |
          curl -s https://chriscarini.com/developer_insights/data.json?project=our-test-project | jq . | tee data.json

      - uses: ./.github/actions/github-pull-request-reminder
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
